#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    vim_help_language = "cn"
    # autocomplete_method="nvim-cmp"
#[[custom_plugins]]
#  repo='https://github.com/hrsh7th/nvim-cmp.git'
#  merged=0
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# Enable Chinese layer
[[layers]]
name = "chinese"
# Enable verilog layer
[[layers]]
name = "lang#verilog"
enable = true
# Enable C/Cpp layer
[[layers]]
name = "lang#C"
enable = true
# Enable tools layer
[[layers]]
name = "tools"
enable = true
# Enable matlab layer
[[layers]]
name = "lang#matlab"
enable = true
# Enable python layer
[[layers]]
name = "lang#python"
enable = true
format_on_save = 1
enable_typeinfo = true;
python_file_head = [
  '#!/usr/bin/env python',
  '# -*- coding: utf-8 -*-',
  '',
  ''
]
# Enable lsp layer
[[layers]]
name = 'lsp'
enabled_clients = ['pylsp']
[layers.override_client_cmds]
  pylsp = ["pylsp"]


